language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    secure: ZVjngag+tfsp++ohG/7dmzqdI8M20ZemYrhEpRk/1j1mTsJfdjED4YTTzBrSHld5Qc5Lq3HNPqpqwiKjxMtBdLi04vWi9PuvIStYYa6uWFBKv1m4+SGYXbyFa70uFtjtiI8X9eakRDocT2syiZqS2xafkVFHHTPCRcod1mUBQ7E=

services:
  - memcached
  - redis-server

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: vendor/bin/phpunit -c . --coverage-clover build/logs/clover.xml
    - script: vendor/bin/phpstan analyse src/ --level 5 --no-progress
      name: "Static Analyser"

before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = igbinary.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - composer install

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
