language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0

addons:
  code_climate:
    repo_token: f250f6c653cfb19fe7460f186f46added2b5b57cf4b4255bbe63685dbff7d88e

services: memcache

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer install

script: vendor/bin/phpunit -c . --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter