language: php

php:
  - 7.2
  - 7.3
  - 7.4

addons:
  code_climate:
    repo_token: f250f6c653cfb19fe7460f186f46added2b5b57cf4b4255bbe63685dbff7d88e

services:
  - memcached
  - redis-server

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: vendor/bin/phpunit -c . --coverage-clover build/logs/clover.xml
    - script: vendor/bin/phpstan analyse src/ --level 5 --no-progress
      name: "Static Analyser"

before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = igbinary.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

after_script:
  - vendor/bin/test-reporter
